#include "meta/headers.hpp"


/***********************************************************************
     * pairAction

***********************************************************************/
ach::Pair pairAction[] =
{
	{.num = ach::ControlAction::caUp   , .str = "Up"   },
	{.num = ach::ControlAction::caDown , .str = "Down" },
	{.num = ach::ControlAction::caLeft , .str = "Left" },
	{.num = ach::ControlAction::caRight, .str = "Right"},
	{.num = ach::ControlAction::caJump , .str = "Jump" },
	{.num = ach::ControlAction::caMenu , .str = "Menu" },

	{.num = ach::ControlAction::caCount, .str = NULL   },
};



/***********************************************************************
     * pairKey

***********************************************************************/
ach::Pair pairKey[] =
{
	{.num = sf::Keyboard::A        , .str = "A"        },
	{.num = sf::Keyboard::B        , .str = "B"        },
	{.num = sf::Keyboard::C        , .str = "C"        },
	{.num = sf::Keyboard::D        , .str = "D"        },
	{.num = sf::Keyboard::E        , .str = "E"        },
	{.num = sf::Keyboard::F        , .str = "F"        },
	{.num = sf::Keyboard::G        , .str = "G"        },
	{.num = sf::Keyboard::H        , .str = "H"        },
	{.num = sf::Keyboard::I        , .str = "I"        },
	{.num = sf::Keyboard::J        , .str = "J"        },
	{.num = sf::Keyboard::K        , .str = "K"        },
	{.num = sf::Keyboard::L        , .str = "L"        },
	{.num = sf::Keyboard::M        , .str = "M"        },
	{.num = sf::Keyboard::N        , .str = "N"        },
	{.num = sf::Keyboard::O        , .str = "O"        },
	{.num = sf::Keyboard::P        , .str = "P"        },
	{.num = sf::Keyboard::Q        , .str = "Q"        },
	{.num = sf::Keyboard::R        , .str = "R"        },
	{.num = sf::Keyboard::S        , .str = "S"        },
	{.num = sf::Keyboard::T        , .str = "T"        },
	{.num = sf::Keyboard::U        , .str = "U"        },
	{.num = sf::Keyboard::V        , .str = "V"        },
	{.num = sf::Keyboard::W        , .str = "W"        },
	{.num = sf::Keyboard::X        , .str = "X"        },
	{.num = sf::Keyboard::Y        , .str = "Y"        },
	{.num = sf::Keyboard::Z        , .str = "Z"        },
	{.num = sf::Keyboard::Num0     , .str = "0"        },
	{.num = sf::Keyboard::Num1     , .str = "1"        },
	{.num = sf::Keyboard::Num2     , .str = "2"        },
	{.num = sf::Keyboard::Num3     , .str = "3"        },
	{.num = sf::Keyboard::Num4     , .str = "4"        },
	{.num = sf::Keyboard::Num5     , .str = "5"        },
	{.num = sf::Keyboard::Num6     , .str = "6"        },
	{.num = sf::Keyboard::Num7     , .str = "7"        },
	{.num = sf::Keyboard::Num8     , .str = "8"        },
	{.num = sf::Keyboard::Num9     , .str = "9"        },
	{.num = sf::Keyboard::Escape   , .str = "ESC"      },
	{.num = sf::Keyboard::LControl , .str = "L-CTRL"   },
	{.num = sf::Keyboard::LShift   , .str = "L-SHIFT"  },
	{.num = sf::Keyboard::LAlt     , .str = "L-ALT"    },
	{.num = sf::Keyboard::LSystem  , .str = "L-WIN"    },
	{.num = sf::Keyboard::RControl , .str = "R-CTRL"   },
	{.num = sf::Keyboard::RShift   , .str = "R-SHIFT"  },
	{.num = sf::Keyboard::RAlt     , .str = "R-ALT"    },
	{.num = sf::Keyboard::RSystem  , .str = "R-WIN"    },
	{.num = sf::Keyboard::Menu     , .str = "MENU"     },
	{.num = sf::Keyboard::LBracket , .str = "["        },
	{.num = sf::Keyboard::RBracket , .str = "]"        },
	{.num = sf::Keyboard::SemiColon, .str = ";"        },
	{.num = sf::Keyboard::Comma    , .str = ","        },
	{.num = sf::Keyboard::Period   , .str = "."        },
	{.num = sf::Keyboard::Quote    , .str = "'"        },
	{.num = sf::Keyboard::Slash    , .str = "/"        },
	{.num = sf::Keyboard::BackSlash, .str = "\\"       },
	{.num = sf::Keyboard::Tilde    , .str = "~"        },
	{.num = sf::Keyboard::Equal    , .str = "="        },
	{.num = sf::Keyboard::Dash     , .str = "-"        },
	{.num = sf::Keyboard::Space    , .str = "SPACE"    },
	{.num = sf::Keyboard::Return   , .str = "ENTER"    },
	{.num = sf::Keyboard::BackSpace, .str = "BACKSPACE"},
	{.num = sf::Keyboard::Tab      , .str = "TAB"      },
	{.num = sf::Keyboard::PageUp   , .str = "PAGE-UP"  },
	{.num = sf::Keyboard::PageDown , .str = "PAGE-DOWN"},
	{.num = sf::Keyboard::End      , .str = "END"      },
	{.num = sf::Keyboard::Home     , .str = "HOME"     },
	{.num = sf::Keyboard::Insert   , .str = "INSERT"   },
	{.num = sf::Keyboard::Delete   , .str = "DELETE"   },
	{.num = sf::Keyboard::Add      , .str = "NUM+"     },
	{.num = sf::Keyboard::Subtract , .str = "NUM-"     },
	{.num = sf::Keyboard::Multiply , .str = "NUM*"     },
	{.num = sf::Keyboard::Divide   , .str = "NUM/"     },
	{.num = sf::Keyboard::Left     , .str = "LEFT"     },
	{.num = sf::Keyboard::Right    , .str = "RIGHT"    },
	{.num = sf::Keyboard::Up       , .str = "UP"       },
	{.num = sf::Keyboard::Down     , .str = "DOWN"     },
	{.num = sf::Keyboard::Numpad0  , .str = "NUM0"     },
	{.num = sf::Keyboard::Numpad1  , .str = "NUM1"     },
	{.num = sf::Keyboard::Numpad2  , .str = "NUM2"     },
	{.num = sf::Keyboard::Numpad3  , .str = "NUM3"     },
	{.num = sf::Keyboard::Numpad4  , .str = "NUM4"     },
	{.num = sf::Keyboard::Numpad5  , .str = "NUM5"     },
	{.num = sf::Keyboard::Numpad6  , .str = "NUM6"     },
	{.num = sf::Keyboard::Numpad7  , .str = "NUM7"     },
	{.num = sf::Keyboard::Numpad8  , .str = "NUM8"     },
	{.num = sf::Keyboard::Numpad9  , .str = "NUM9"     },
	{.num = sf::Keyboard::F1       , .str = "F1"       },
	{.num = sf::Keyboard::F2       , .str = "F2"       },
	{.num = sf::Keyboard::F3       , .str = "F3"       },
	{.num = sf::Keyboard::F4       , .str = "F4"       },
	{.num = sf::Keyboard::F5       , .str = "F5"       },
	{.num = sf::Keyboard::F6       , .str = "F6"       },
	{.num = sf::Keyboard::F7       , .str = "F7"       },
	{.num = sf::Keyboard::F8       , .str = "F8"       },
	{.num = sf::Keyboard::F9       , .str = "F9"       },
	{.num = sf::Keyboard::F10      , .str = "F10"      },
	{.num = sf::Keyboard::F11      , .str = "F11"      },
	{.num = sf::Keyboard::F12      , .str = "F12"      },
	{.num = sf::Keyboard::F13      , .str = "F13"      },
	{.num = sf::Keyboard::F14      , .str = "F14"      },
	{.num = sf::Keyboard::F15      , .str = "F15"      },
	{.num = sf::Keyboard::Pause    , .str = "PAUSE"    },

	{.num = sf::Keyboard::Unknown  , .str = NULL       },
};
