#include "meta/headers.hpp"


/***********************************************************************
     * pairAction

***********************************************************************/
ach::Pair<ach::ControlAction> pairAction[] =
{
	{.num = ach::ControlAction::caUp   , .str = "Up"   },
	{.num = ach::ControlAction::caDown , .str = "Down" },
	{.num = ach::ControlAction::caLeft , .str = "Left" },
	{.num = ach::ControlAction::caRight, .str = "Right"},
	{.num = ach::ControlAction::caJump , .str = "Jump" },
	{.num = ach::ControlAction::caMenu , .str = "Menu" },

	{.num = ach::ControlAction::caCount, .str = NULL   },
};



/***********************************************************************
     * pairJoy

***********************************************************************/
ach::Pair<ach::JoystickCode> pairJoy[] =
{
	{.num = ach::JoystickCode::jcAxisXminus   , .str = "X -"   },
	{.num = ach::JoystickCode::jcAxisXplus    , .str = "X +"   },
	{.num = ach::JoystickCode::jcAxisYminus   , .str = "Y -"   },
	{.num = ach::JoystickCode::jcAxisYplus    , .str = "Y +"   },
	{.num = ach::JoystickCode::jcAxisZminus   , .str = "Z -"   },
	{.num = ach::JoystickCode::jcAxisZplus    , .str = "Z +"   },
	{.num = ach::JoystickCode::jcAxisRminus   , .str = "R -"   },
	{.num = ach::JoystickCode::jcAxisRplus    , .str = "R +"   },
	{.num = ach::JoystickCode::jcAxisUminus   , .str = "U -"   },
	{.num = ach::JoystickCode::jcAxisUplus    , .str = "U +"   },
	{.num = ach::JoystickCode::jcAxisVminus   , .str = "V -"   },
	{.num = ach::JoystickCode::jcAxisVplus    , .str = "V +"   },
	{.num = ach::JoystickCode::jcAxisPovXminus, .str = "PovX -"},
	{.num = ach::JoystickCode::jcAxisPovXplus , .str = "PovX +"},
	{.num = ach::JoystickCode::jcAxisPovYminus, .str = "PovY -"},
	{.num = ach::JoystickCode::jcAxisPovYplus , .str = "PovY +"},
	{.num = ach::JoystickCode::jcButton1      , .str = "B 01"  },
	{.num = ach::JoystickCode::jcButton2      , .str = "B 02"  },
	{.num = ach::JoystickCode::jcButton3      , .str = "B 03"  },
	{.num = ach::JoystickCode::jcButton4      , .str = "B 04"  },
	{.num = ach::JoystickCode::jcButton5      , .str = "B 05"  },
	{.num = ach::JoystickCode::jcButton6      , .str = "B 06"  },
	{.num = ach::JoystickCode::jcButton7      , .str = "B 07"  },
	{.num = ach::JoystickCode::jcButton8      , .str = "B 08"  },
	{.num = ach::JoystickCode::jcButton9      , .str = "B 09"  },
	{.num = ach::JoystickCode::jcButton10     , .str = "B 10"  },
	{.num = ach::JoystickCode::jcButton11     , .str = "B 11"  },
	{.num = ach::JoystickCode::jcButton12     , .str = "B 12"  },
	{.num = ach::JoystickCode::jcButton13     , .str = "B 13"  },
	{.num = ach::JoystickCode::jcButton14     , .str = "B 14"  },
	{.num = ach::JoystickCode::jcButton15     , .str = "B 15"  },
	{.num = ach::JoystickCode::jcButton16     , .str = "B 16"  },
	{.num = ach::JoystickCode::jcButton17     , .str = "B 17"  },
	{.num = ach::JoystickCode::jcButton18     , .str = "B 18"  },
	{.num = ach::JoystickCode::jcButton19     , .str = "B 19"  },
	{.num = ach::JoystickCode::jcButton20     , .str = "B 20"  },
	{.num = ach::JoystickCode::jcButton21     , .str = "B 21"  },
	{.num = ach::JoystickCode::jcButton22     , .str = "B 22"  },
	{.num = ach::JoystickCode::jcButton23     , .str = "B 23"  },
	{.num = ach::JoystickCode::jcButton24     , .str = "B 24"  },
	{.num = ach::JoystickCode::jcButton25     , .str = "B 25"  },
	{.num = ach::JoystickCode::jcButton26     , .str = "B 26"  },
	{.num = ach::JoystickCode::jcButton27     , .str = "B 27"  },
	{.num = ach::JoystickCode::jcButton28     , .str = "B 28"  },
	{.num = ach::JoystickCode::jcButton29     , .str = "B 29"  },
	{.num = ach::JoystickCode::jcButton30     , .str = "B 30"  },
	{.num = ach::JoystickCode::jcButton31     , .str = "B 31"  },
	{.num = ach::JoystickCode::jcButton32     , .str = "B 32"  },

	{.num = ach::JoystickCode::jcCount        , .str = NULL    },
};



/***********************************************************************
     * pairKey

***********************************************************************/
ach::Pair<sf::Keyboard::Key> pairKey[] =
{
	{.num = sf::Keyboard::A        , .str = "A"        },
	{.num = sf::Keyboard::B        , .str = "B"        },
	{.num = sf::Keyboard::C        , .str = "C"        },
	{.num = sf::Keyboard::D        , .str = "D"        },
	{.num = sf::Keyboard::E        , .str = "E"        },
	{.num = sf::Keyboard::F        , .str = "F"        },
	{.num = sf::Keyboard::G        , .str = "G"        },
	{.num = sf::Keyboard::H        , .str = "H"        },
	{.num = sf::Keyboard::I        , .str = "I"        },
	{.num = sf::Keyboard::J        , .str = "J"        },
	{.num = sf::Keyboard::K        , .str = "K"        },
	{.num = sf::Keyboard::L        , .str = "L"        },
	{.num = sf::Keyboard::M        , .str = "M"        },
	{.num = sf::Keyboard::N        , .str = "N"        },
	{.num = sf::Keyboard::O        , .str = "O"        },
	{.num = sf::Keyboard::P        , .str = "P"        },
	{.num = sf::Keyboard::Q        , .str = "Q"        },
	{.num = sf::Keyboard::R        , .str = "R"        },
	{.num = sf::Keyboard::S        , .str = "S"        },
	{.num = sf::Keyboard::T        , .str = "T"        },
	{.num = sf::Keyboard::U        , .str = "U"        },
	{.num = sf::Keyboard::V        , .str = "V"        },
	{.num = sf::Keyboard::W        , .str = "W"        },
	{.num = sf::Keyboard::X        , .str = "X"        },
	{.num = sf::Keyboard::Y        , .str = "Y"        },
	{.num = sf::Keyboard::Z        , .str = "Z"        },
	{.num = sf::Keyboard::Num0     , .str = "0"        },
	{.num = sf::Keyboard::Num1     , .str = "1"        },
	{.num = sf::Keyboard::Num2     , .str = "2"        },
	{.num = sf::Keyboard::Num3     , .str = "3"        },
	{.num = sf::Keyboard::Num4     , .str = "4"        },
	{.num = sf::Keyboard::Num5     , .str = "5"        },
	{.num = sf::Keyboard::Num6     , .str = "6"        },
	{.num = sf::Keyboard::Num7     , .str = "7"        },
	{.num = sf::Keyboard::Num8     , .str = "8"        },
	{.num = sf::Keyboard::Num9     , .str = "9"        },
	{.num = sf::Keyboard::Escape   , .str = "ESC"      },
	{.num = sf::Keyboard::LControl , .str = "L-CTRL"   },
	{.num = sf::Keyboard::LShift   , .str = "L-SHIFT"  },
	{.num = sf::Keyboard::LAlt     , .str = "L-ALT"    },
	{.num = sf::Keyboard::LSystem  , .str = "L-WIN"    },
	{.num = sf::Keyboard::RControl , .str = "R-CTRL"   },
	{.num = sf::Keyboard::RShift   , .str = "R-SHIFT"  },
	{.num = sf::Keyboard::RAlt     , .str = "R-ALT"    },
	{.num = sf::Keyboard::RSystem  , .str = "R-WIN"    },
	{.num = sf::Keyboard::Menu     , .str = "MENU"     },
	{.num = sf::Keyboard::LBracket , .str = "["        },
	{.num = sf::Keyboard::RBracket , .str = "]"        },
	{.num = sf::Keyboard::SemiColon, .str = ";"        },
	{.num = sf::Keyboard::Comma    , .str = ","        },
	{.num = sf::Keyboard::Period   , .str = "."        },
	{.num = sf::Keyboard::Quote    , .str = "'"        },
	{.num = sf::Keyboard::Slash    , .str = "/"        },
	{.num = sf::Keyboard::BackSlash, .str = "\\"       },
	{.num = sf::Keyboard::Tilde    , .str = "~"        },
	{.num = sf::Keyboard::Equal    , .str = "="        },
	{.num = sf::Keyboard::Dash     , .str = "-"        },
	{.num = sf::Keyboard::Space    , .str = "SPACE"    },
	{.num = sf::Keyboard::Return   , .str = "ENTER"    },
	{.num = sf::Keyboard::BackSpace, .str = "BACKSPACE"},
	{.num = sf::Keyboard::Tab      , .str = "TAB"      },
	{.num = sf::Keyboard::PageUp   , .str = "PAGE-UP"  },
	{.num = sf::Keyboard::PageDown , .str = "PAGE-DOWN"},
	{.num = sf::Keyboard::End      , .str = "END"      },
	{.num = sf::Keyboard::Home     , .str = "HOME"     },
	{.num = sf::Keyboard::Insert   , .str = "INSERT"   },
	{.num = sf::Keyboard::Delete   , .str = "DELETE"   },
	{.num = sf::Keyboard::Add      , .str = "NUM+"     },
	{.num = sf::Keyboard::Subtract , .str = "NUM-"     },
	{.num = sf::Keyboard::Multiply , .str = "NUM*"     },
	{.num = sf::Keyboard::Divide   , .str = "NUM/"     },
	{.num = sf::Keyboard::Left     , .str = "LEFT"     },
	{.num = sf::Keyboard::Right    , .str = "RIGHT"    },
	{.num = sf::Keyboard::Up       , .str = "UP"       },
	{.num = sf::Keyboard::Down     , .str = "DOWN"     },
	{.num = sf::Keyboard::Numpad0  , .str = "NUM0"     },
	{.num = sf::Keyboard::Numpad1  , .str = "NUM1"     },
	{.num = sf::Keyboard::Numpad2  , .str = "NUM2"     },
	{.num = sf::Keyboard::Numpad3  , .str = "NUM3"     },
	{.num = sf::Keyboard::Numpad4  , .str = "NUM4"     },
	{.num = sf::Keyboard::Numpad5  , .str = "NUM5"     },
	{.num = sf::Keyboard::Numpad6  , .str = "NUM6"     },
	{.num = sf::Keyboard::Numpad7  , .str = "NUM7"     },
	{.num = sf::Keyboard::Numpad8  , .str = "NUM8"     },
	{.num = sf::Keyboard::Numpad9  , .str = "NUM9"     },
	{.num = sf::Keyboard::F1       , .str = "F1"       },
	{.num = sf::Keyboard::F2       , .str = "F2"       },
	{.num = sf::Keyboard::F3       , .str = "F3"       },
	{.num = sf::Keyboard::F4       , .str = "F4"       },
	{.num = sf::Keyboard::F5       , .str = "F5"       },
	{.num = sf::Keyboard::F6       , .str = "F6"       },
	{.num = sf::Keyboard::F7       , .str = "F7"       },
	{.num = sf::Keyboard::F8       , .str = "F8"       },
	{.num = sf::Keyboard::F9       , .str = "F9"       },
	{.num = sf::Keyboard::F10      , .str = "F10"      },
	{.num = sf::Keyboard::F11      , .str = "F11"      },
	{.num = sf::Keyboard::F12      , .str = "F12"      },
	{.num = sf::Keyboard::F13      , .str = "F13"      },
	{.num = sf::Keyboard::F14      , .str = "F14"      },
	{.num = sf::Keyboard::F15      , .str = "F15"      },
	{.num = sf::Keyboard::Pause    , .str = "PAUSE"    },

	{.num = sf::Keyboard::Unknown  , .str = NULL       },
};
