#!/bin/bash

function help() {
	echo -e "Syntax: $0 <t> <path> (class)"
	echo -e "\tt = [s i b] - src, include, both"
	echo -e "\tpath - prefix"
	echo -e "\class - optional class name"
	exit
}


function inc() {
	mkdir -p include/`dirname "$1"`

	GUARD=`echo ${1^^} | sed "s/\//_/g"`

	cat <<EOF > include/$1.hpp
#ifndef __$GUARD
#define __$GUARD


namespace ach
{
	struct $2
	{
		 $2();
		~$2();
	};
}

#endif
EOF
}


function src() {
	mkdir -p src/`dirname "$1"`

	cat <<EOF > src/$1.cpp
#include "meta/headers.hpp"


/***********************************************************************
     * $2
     * constructor

***********************************************************************/
ach::$2::$2()
{
}



/***********************************************************************
     * $2
     * destructor

***********************************************************************/
ach::$2::~$2()
{
}
EOF
}


if [ ! -z "$3" ]; then
	CLASS="$3"
else
	CLASS="Class"
fi


if [ "$1" = "s" ]; then
	src "$2" "$CLASS"
elif [ "$1" = "i" ]; then
	inc "$2" "$CLASS"
elif [ "$1" = "b" ]; then
	src "$2" "$CLASS"
	inc "$2" "$CLASS"
else
	help
fi
